// <auto-generated />
using System;
using Cocktails.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cocktails.Persistence.Migrations
{
    [DbContext(typeof(CocktailsDbContext))]
    partial class CocktailsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Cocktails.Domain.FavoriteCocktail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FavoriteCocktails");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7854),
                            ImageURL = "https://www.liquor.com/thmb/V5L3hv-w8ph2_RQi_-simg-4Ris=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Frozen-Margarita-1500x1500-hero-191e49b3ab4f4781b93f3cfacac25136.jpg",
                            Name = "Margarita",
                            UserId = "tester"
                        },
                        new
                        {
                            Id = 101,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7857),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Bloody Mary",
                            UserId = "tester"
                        },
                        new
                        {
                            Id = 102,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7858),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Test2",
                            UserId = "tester"
                        },
                        new
                        {
                            Id = 103,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7859),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Bloody Mary",
                            UserId = "tester"
                        },
                        new
                        {
                            Id = 104,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7859),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Some Drink",
                            UserId = "tester"
                        },
                        new
                        {
                            Id = 105,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7860),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Fifth one",
                            UserId = "tester"
                        },
                        new
                        {
                            Id = 106,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7861),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Testing 6th",
                            UserId = "tester"
                        },
                        new
                        {
                            Id = 107,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7862),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Another Margarita",
                            UserId = "tester"
                        },
                        new
                        {
                            Id = 108,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7862),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Third Margarita",
                            UserId = "tester"
                        },
                        new
                        {
                            Id = 109,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7863),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Fourth Margarita",
                            UserId = "tester"
                        },
                        new
                        {
                            Id = 110,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7864),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Third Bloody Mary",
                            UserId = "tester"
                        },
                        new
                        {
                            Id = 111,
                            DateCreated = new DateTime(2024, 3, 14, 7, 44, 26, 936, DateTimeKind.Utc).AddTicks(7865),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Final test drink",
                            UserId = "111"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
