// <auto-generated />
using System;
using Cocktails.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cocktails.Persistence.Migrations
{
    [DbContext(typeof(CocktailsDbContext))]
    partial class CocktailsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Cocktails.Domain.FavoriteCocktail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CocktailId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FavoriteCocktails");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CocktailId = 111,
                            DateCreated = new DateTime(2024, 3, 24, 11, 19, 5, 356, DateTimeKind.Utc).AddTicks(5814),
                            ImageURL = "https://www.liquor.com/thmb/V5L3hv-w8ph2_RQi_-simg-4Ris=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Frozen-Margarita-1500x1500-hero-191e49b3ab4f4781b93f3cfacac25136.jpg",
                            Name = "Margarita",
                            UserId = "ee19ebca-901a-4ce9-a435-6b074db12f9f"
                        },
                        new
                        {
                            Id = 101,
                            CocktailId = 111,
                            DateCreated = new DateTime(2024, 3, 24, 11, 19, 5, 356, DateTimeKind.Utc).AddTicks(5823),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Bloody Mary",
                            UserId = "ee19ebca-901a-4ce9-a435-6b074db12f9f"
                        },
                        new
                        {
                            Id = 102,
                            CocktailId = 111,
                            DateCreated = new DateTime(2024, 3, 24, 11, 19, 5, 356, DateTimeKind.Utc).AddTicks(5825),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Test2",
                            UserId = "ee19ebca-901a-4ce9-a435-6b074db12f9f"
                        },
                        new
                        {
                            Id = 103,
                            CocktailId = 111,
                            DateCreated = new DateTime(2024, 3, 24, 11, 19, 5, 356, DateTimeKind.Utc).AddTicks(5826),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Bloody Mary",
                            UserId = "ee19ebca-901a-4ce9-a435-6b074db12f9f"
                        },
                        new
                        {
                            Id = 104,
                            CocktailId = 111,
                            DateCreated = new DateTime(2024, 3, 24, 11, 19, 5, 356, DateTimeKind.Utc).AddTicks(5826),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Some Drink",
                            UserId = "ee19ebca-901a-4ce9-a435-6b074db12f9f"
                        },
                        new
                        {
                            Id = 105,
                            CocktailId = 111,
                            DateCreated = new DateTime(2024, 3, 24, 11, 19, 5, 356, DateTimeKind.Utc).AddTicks(5827),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Fifth one",
                            UserId = "ee19ebca-901a-4ce9-a435-6b074db12f9f"
                        },
                        new
                        {
                            Id = 106,
                            CocktailId = 111,
                            DateCreated = new DateTime(2024, 3, 24, 11, 19, 5, 356, DateTimeKind.Utc).AddTicks(5828),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Testing 6th",
                            UserId = "ee19ebca-901a-4ce9-a435-6b074db12f9f"
                        },
                        new
                        {
                            Id = 107,
                            CocktailId = 111,
                            DateCreated = new DateTime(2024, 3, 24, 11, 19, 5, 356, DateTimeKind.Utc).AddTicks(5829),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Another Margarita",
                            UserId = "a9dc8882-1d14-493a-9e18-2c604d043c8b"
                        },
                        new
                        {
                            Id = 108,
                            CocktailId = 111,
                            DateCreated = new DateTime(2024, 3, 24, 11, 19, 5, 356, DateTimeKind.Utc).AddTicks(5830),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Third Margarita",
                            UserId = "a9dc8882-1d14-493a-9e18-2c604d043c8b"
                        },
                        new
                        {
                            Id = 109,
                            CocktailId = 111,
                            DateCreated = new DateTime(2024, 3, 24, 11, 19, 5, 356, DateTimeKind.Utc).AddTicks(5831),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Fourth Margarita",
                            UserId = "a9dc8882-1d14-493a-9e18-2c604d043c8b"
                        },
                        new
                        {
                            Id = 110,
                            CocktailId = 111,
                            DateCreated = new DateTime(2024, 3, 24, 11, 19, 5, 356, DateTimeKind.Utc).AddTicks(5832),
                            ImageURL = "https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/1202_1_1439206245.jpg?tr=w-800,h-1066",
                            Name = "Third Bloody Mary",
                            UserId = "a9dc8882-1d14-493a-9e18-2c604d043c8b"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ee19ebca-901a-4ce9-a435-6b074db12f9f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c97d323f-1a88-4615-a24a-c5275e29449c",
                            Email = "john@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN@TEST.COM",
                            NormalizedUserName = "JOHN",
                            PasswordHash = "AQAAAAIAAYagAAAAECHR/9NuWnF7y4CPK5SlpKpsO3uP842b1V0JMY3HBJjBaASUc+yq9O1uAxqW0paogg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dfe41b09-9f88-4a6b-aaeb-5ac575983715",
                            TwoFactorEnabled = false,
                            UserName = "John"
                        },
                        new
                        {
                            Id = "a9dc8882-1d14-493a-9e18-2c604d043c8b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c201f609-8bae-4593-bc84-ddcb337c5e91",
                            Email = "jane@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE@TEST.COM",
                            NormalizedUserName = "JANE",
                            PasswordHash = "AQAAAAIAAYagAAAAEFurvpus4koap3XJ+hgApBW0ldQQWgyhogI7NYKeK3S+m/MzBInK4LMtKueiIOxp5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "86e5503d-e6eb-40a3-99b6-a0549da71976",
                            TwoFactorEnabled = false,
                            UserName = "Jane"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
